export const ROLES = {
    INSTRUCTOR: 3,
    CO_INSTRUCTOR: 5,
    MANAGEMENT: 2,
    AMBASSADOR: 7,
    EDUCATION_ADMIN: 8,
    EDUCATION_OFFICER: 9,
    ADMISSION_ADVISOR: 6,
    FINANCE_OFFICER: 4,
    CURRICULUM_DEVELOPER: 10,
    FINANCE_ADMIN: 12,
};
